version: "3.8"
services:
  postgres:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    container_name: postgres_dev
    environment: 
      - POSTGRES_PASSWORD=postgres
  pgadmin:
    image: thajeztah/pgadmin4
    ports: 
      - "5050:5050"
    container_name: pgadmin_dev